server:
  port: ${SPRING_SERVER_PORT:1888}

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/cert_vault?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:cert_vault}
    password: ${SPRING_DATASOURCE_PASSWORD:cert_2025_vault}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:127.0.0.1}
      port: ${SPRING_REDIS_PORT:6379}
      database: ${SPRING_REDIS_DATABASE:8}
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 30000
      client-type: lettuce
      lettuce:
        pool:
          max-active: 10
          min-idle: 5
  cache:
    type: redis
    redis:
      cache-null-values: true
      key-prefix: "cache:"
      use-key-prefix: true
      time-to-live: 5m
  sql:
    init:
      platform: ${DATABASE_TYPE:mysql}
      mode: always
      schema-locations: classpath:/sql/schema-${DATABASE_TYPE:mysql}.sql
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${OIDC_CLIENT_ID:cert-vault}
            client-secret: ${OIDC_CLIENT_SECRET:changeme}
            scope: ${OIDC_SCOPE:openid,email,profile}
            redirect-uri: "${SERVER_BASE_URL:http://127.0.0.1:1888}/api/v1/auth/oauth/callback"
            authorization-grant-type: authorization_code
            provider: oidc
            client-authentication-method: client_secret_basic
        provider:
          oidc:
            token-uri: "${OIDC_TOKEN_URI:https://127.0.0.1:8443/realms/cert-vault/protocol/openid-connect/token}"
            authorization-uri: "${OIDC_AUTHORIZATION_URI:https://127.0.0.1:8443/realms/cert-vault/protocol/openid-connect/auth}"
            user-info-uri: "${OIDC_USER_INFO_URI:https://127.0.0.1:8443/realms/cert-vault/protocol/openid-connect/userinfo}"
            jwk-set-uri: "${OIDC_JWK_SET_URI:https://127.0.0.1:8443/realms/cert-vault/protocol/openid-connect/certs}"
            user-name-attribute: "${OIDC_USERNAME_ATTRIBUTE:preferred_username}"

oidc:
  enabled: ${ENABLE_OIDC:true}
  provider: "${OIDC_PROVIDER:OpenID Connect}"
  logo: "${OIDC_LOGO:data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjwhRE9DVFlQRSBzdmcgIFBVQkxJQyAnLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4nICAnaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkJz48c3ZnIGhlaWdodD0iNTEycHgiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDUxMiA1MTI7IiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiB3aWR0aD0iNTEycHgiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxnIGlkPSJfeDMyXzM5LW9wZW5pZCI+PGc+PHBhdGggZD0iTTIzNC44NDksNDE5djYuNjIzYy03OS4yNjgtOS45NTgtMTM5LjMzNC01My4zOTMtMTM5LjMzNC0xMDUuNzU3ICAgIGMwLTM5LjMxMywzMy44NzMtNzMuNTk1LDg0LjQ4NS05Mi41MTFMMTc4LjAyMywxODBDODguODkyLDIwMi40OTcsMjYuMDAxLDI1Ni42MDcsMjYuMDAxLDMxOS44NjYgICAgYzAsNzYuMjg4LDkwLjg3MSwxMzkuMTI4LDIwOC45NSwxNDkuNzA1bDAuMDE4LTAuMDA5VjQxOUgyMzQuODQ5eiIgc3R5bGU9ImZpbGw6I0IyQjJCMjsiLz48cG9seWdvbiBwb2ludHM9IjMwNC43NzIsNDM2LjcxMyAzMDQuNjcsNDM2LjcxMyAzMDQuNjcsMjIxLjY2NyAzMDQuNjcsMjEzLjY2NyAzMDQuNjcsNDIuNDI5ICAgICAyMzQuODQ5LDc4LjI1IDIzNC44NDksMjIxLjY2NyAyMzQuOTY5LDIyMS42NjcgMjM0Ljk2OSw0NjkuNTYzICAgIiBzdHlsZT0iZmlsbDojRjc5MzFFOyIvPjxwYXRoIGQ9Ik00ODUuOTk5LDI5MS45MzhsLTkuNDQ2LTEwMC4xMTRsLTM1LjkzOCwyMC4zMzFDNDE1LjA4NywxOTYuNjQ5LDM4Mi41LDE3Ny41LDM0MCwxNzcuMjYxICAgIGwwLjAwMiwzNi40MDZ2Ny40OThjMy41MDIsMC45NjgsNi45MjMsMi4wMjQsMTAuMzAxLDMuMTI1YzE0LjE0NSw0LjYxMSwyNy4xNzYsMTAuMzUyLDM4LjY2NiwxNy4xMjhsLTM3Ljc4NiwyMS4yNTQgICAgTDQ4NS45OTksMjkxLjkzOHoiIHN0eWxlPSJmaWxsOiNCMkIyQjI7Ii8+PC9nPjwvZz48ZyBpZD0iTGF5ZXJfMSIvPjwvc3ZnPg==}"

logging:
  level:
    com.gregperlinli.certvault: ${SPRING_LOGGING_LEVEL_COM_GREGPERLINLI_CERTVAULT:debug}
    org.springframework: ${SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:warn}

management:
  server:
    port: ${SPRING_MANAGEMENT_SERVER_PORT:1999}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"

mybatis-plus:
  type-aliases-package: com.gregperlinli.certvault.domain.entities
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: ${SPRING_API_DOCS_ENABLED:true}
    path: /api/docs
  swagger-ui:
    path: /devcenter-api
  packages-to-scan:
    - com.gregperlinli.certvault.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

init:
  superadmin:
    username: ${SUPERADMIN_USERNAME:superadmin}
    display-name: ${SUPERADMIN_DISPLAY_NAME:Default Superadmin}
    email: ${SUPERADMIN_EMAIL:superadmin@certvault.example}
    password: ${SUPERADMIN_PASSWORD:CertVault@2025}

encrypt:
  rsa:
    key:
      public-key: ${SPRING_RSA_PUBLIC_KEY:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnj/4CyjvJNfqtB5JsPnOWb/ylG/BL58hdsfKWmwzUEma1YibR1JYzLnJPISAimeOBm7sGSaSu4e582qzeutSZtzTUNGI9k8gfHItYZyCwyveYqBG6c3dG4XOQa/Ge8pUo2zf19ZvghBL3IjvhRzLuffmPZ9Ok8UnhBlPGRyr1nQIDAQAB}
      private-key: ${SPRING_RSA_PRIVATE_KEY:MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKeP/gLKO8k1+q0Hkmw+c5Zv/KUb8EvnyF2x8pabDNQSZrViJtHUljMuck8hICKZ44GbuwZJpK7h7nzarN661Jm3NNQ0Yj2TyB8ci1hnILDK95ioEbpzd0bhc5Br8Z7ylSjbN/X1m+CEEvciO+FHMu59+Y9n06TxSeEGU8ZHKvWdAgMBAAECgYAZLyEkVjTqJvzIKM0vC6vfvnEgd7SEFBAfVPF7BU7GSQW62UewXd09UAvKLNZhnPN+tWNErKjdyANKLKuyxi3Rtexf9CCrp7JWo7poYpOPfZ80e1UINU3HlIfWDQxD12ppy7VobblepA2tFjx12QrAs+42ygqt78khDa15sc3nWQJBAOmJlITXuqwoXX/8QXXhdEvgyVTg2tk4ySWS5/0Jtn2JFFZ0o2Q8oe2yc1TPsmzQOPImxVXbMiBDTLasB0Ivh2sCQQC3recmttsNhHVNuwJv0alPqmClb3gM3BITbTIoDKJy6M5yYgNSRiD5Vo6d0io9ZCvVjwqEtBiEBB1PBIvWkyEXAkEA4bc1sseHBsnkxMScyEBl1MioDr9dBkIaN5SrYCe5F9Abtgv5t/HaWBD342ry+rSttW2/oOHAquohBRVz1oZ1jQJAdtbbMV8phytmQe52+yXpp5OSiDcAs0FHqK4Dv4m9KR+bQsJLZ9Xby7bG+zFZBvNisP+lTIrBOdj3pYJJf4Ed7QJBAL+LiUx9TE9+M2H0PjxDPtIhIsQfz91VB8VbAtS+p5i2abfTKwv4Aq5ClcinRyQE0OkUzUvju7nsfCqHy32GNtw=}
