version: '3.9'
x-common-certvault: &common_certvault
  image: ghcr.io/gregperlinli/certvault:latest
  ports:
    - ${EXTERNAL_PORT}:1888
  restart: always
  environment:
    TIME_ZONE: ${TIME_ZONE}
    SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
    SUPERADMIN_DISPLAY_NAME: ${SUPERADMIN_DISPLAY_NAME}
    SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL}
    SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
    SPRING_RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
    SPRING_RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
    SPRING_LOGGING_LEVEL_COM_GREGPERLINLI_CERTVAULT: ${SPRING_LOGGING_LEVEL_COM_GREGPERLINLI_CERTVAULT}
    SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}

services:
  cert-vault:
    <<: *common_certvault
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_EXTERNAL_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_EXTERNAL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_EXTERNAL_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_EXTERNAL_HOST}
      SPRING_REDIS_PORT: ${REDIS_EXTERNAL_PORT}
      SPRING_REDIS_DATABASE: ${REDIS_EXTERNAL_DATABASE}
      SPRING_REDIS_PASSWORD: ${REDIS_EXTERNAL_PASSWORD}