name: CertVault Backend Deploy

on:
  push:
    branches:
      - dev
    paths:
      - server/**
#  release:
#    types:
#      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 使用 Maven 打包后端项目
      - name: Build with Maven
        run: mvn clean package -f server/pom.xml

      # 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Docker 镜像
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: server/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#      - name: Build Docker image
#        run: |
#          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f server/pom.xml)
#          docker build -t ghcr.io/gregperlinli/cert-vault:$VERSION -t ghcr.io/gregperlinli/cert-vault:latest server/
#      # 推送 Docker 镜像
#      - name: Push Docker image
#        run: |
#          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f server/pom.xml)
#          docker push ghcr.io/gregperlinli/cert-vault:$VERSION
#          docker push ghcr.io/gregperlinli/cert-vault:latest

  deploy-helm:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 配置 GitHub Pages
      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: server/helm
          commit_message: "Deploy Helm chart"