name: CertVault Backend Deploy

on:
  push:
    branches:
      - dev
    paths:
      - server/**
#  release:
#    types:
#      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 使用 Maven 打包后端项目
      - name: Build with Maven
        run: mvn clean package -f server/pom.xml

      # 获取 Maven 版本并设置为环境变量
      - name: Get Maven version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f server/pom.xml)" >> $GITHUB_ENV

      # 修改 Chart.yaml 文件中的版本字段
      - name: Update Chart.yaml version
        run: |
          sed -i "s/version: 0.0.0/version: ${{ env.VERSION }}/" server/helm/charts/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: \"${{ env.VERSION }}\"/" server/helm/charts/Chart.yaml

      # 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Docker 镜像
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: server/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up environment variable
        run: echo "VERSION=${{ env.VERSION }}" > version.env

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.env

  deploy-helm:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: version
          path: .

      - name: Read environment variable
        run: |
          cat version.env >> $GITHUB_ENV
          echo "The value of VERSION is: ${{ env.VERSION }}"

      # 检出当前代码库
      - name: Checkout code
        uses: actions/checkout@v3

      # 检出目标仓库代码
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: gregPerlinLi/certvault-charts
          token: ${{ secrets.CERT_VAULT_CHARTS_TOKEN }}
          path: certvault-charts
          ref: main

      # 配置 Git 用户信息
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 复制 Helm 目录到目标仓库
      - name: Copy Helm directory to target repository
        run: |
          rm -rf charts .github
          cp -r server/helm/* certvault-charts/
          cp -r server/helm/.github certvault-charts/
          cp server/helm/charts/README.md certvault-charts/README.md
          sed -i "s/version: 0.0.0/version: ${{ env.VERSION }}/" certvault-charts/charts/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: \"${{ env.VERSION }}\"/" certvault-charts/charts/Chart.yaml

      # 提交并推送到目标仓库的 main 分支
      - name: Commit and push to target repository
        run: |
          cd certvault-charts
          git add .
          git commit -m "Update Helm chart from CertVault Backend Deploy" || echo "No changes to commit"
          git push origin main
