name: Frontend CI

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: pwd || ls -la
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Build frontend
        run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: dist
